# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Booking.destroy_all
CarModel.destroy_all
OwnedCar.destroy_all
Review.destroy_all
User.destroy_all
WishListCar.destroy_all


20.times do
    User.create(name: Faker::Name.name , age: Faker::Number.number(digits: 2), driver_id: Faker::IDNumber.valid, address: Faker::Address.full_address , email: Faker::Internet.email, password_digest: Faker::Lorem.paragraph)
end

# 20.times do
#     CarModel.create(category: Faker::Vehicle.car_type, brand: Faker::Vehicle.make, model: Faker::Vehicle.model, description: Faker::Lorem.paragraphs, image_url: Faker::Avatar.image(slug: "my-own-slug",size: "50x50",format: "jpg"))
# end

CarModel.create(category: "sedan", brand: "Porsche", model: "Taycan", description: "After years of teasing, Porsche's new Taycan (pronounced TIE-kahn, not TAY-can) is the brand's first EV as well as the market's first true head-to-head rival for the popular Tesla Model S. The four-seat sedan is also the most expensive and least efficient car on this list, but its desirability is off the charts thanks to extreme performance, sexy design, and a luxurious interior. Currently, every Taycan features all-wheel drive and two powerful electric motors. Porsche offers three models—the 522-hp 4S, the 670-hp Turbo, and the 750-hp Turbo S—but don't let those names throw you. The Turbo and Turbo S aren't actually turbocharged like the brand's gas-powered models, such as the Panamera Turbo and 911 Turbo S. Again, every Taycan is strictly battery powered. The Taycan 4S has an EPA-rated range of 203 miles, while the Turbo and Turbo S offer a little less.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-porsche-taycan-turbo-s-and-2020-tesla-model-s-102-1581027957-1-1589390517.jpg")

CarModel.create(category: "SUV", brand: "Audi", model: "e-tron", description: "Audi's only EV is a five-passenger SUV. It'll soon be available in two body styles: the standard e-tron, which has more cargo space, and the upcoming e-tron Sportback that has a sportier coupelike silhouette. Both are more than nine inches longer than a Q5 and are offered in a couple trim levels. Each has a sizable 95.3-kWh lithium-ion battery pack and two electric motors that generate a combined 355 horsepower and 414 pound-feet of torque. Put the transmission in Sport mode, though, and output jumps to 402 horsepower and 490 pound-feet briefly. All-wheel drive is standard. Unfortunately, the Audi's 74-MPGe rating and 204 miles of range aren't that impressive, but it can hit 60 mph in a claimed 5.5 seconds, so it's quick as well as comfortable. There's also plenty of rear cargo space and a small trunk up front.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/a1916110-medium-1589481592.jpg")

CarModel.create(category: "SUV", brand: "Jaguar", model: "I-Pace", description: "Jaguar's first electric vehicle is now in its second year of sales. The I-Pace competes with the Tesla Model X but costs considerably less. Audi offers three trim levels—S, SE, and HSE—and they all get the same 90.0-kWh lithium-ion battery pack and two electric motors, producing a heady 394 horsepower and 512 pound-feet of torque. All-wheel drive is standard. Although the Jag's 76-MPGe rating isn't much to brag about, its 234-mile range is respectable. That it can hit 60 mph in less than five seconds makes it one of the quickest EVs out there. It's also family friendly, with seating for five, 25 cubic feet of rear cargo space, and a small front trunk.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2019-jaguar-i-pace-first-drive-99leadgallery-1528836796.jpg")

CarModel.create(category: "SUV", brand: "Tesla", model: "Model X", description: "This is the largest and most expensive SUV on this list. It's also the only seven-seater. Famous for its dramatic falcon-wing back doors, the Tesla Model X has been around for five years now, and it hasn't changed much in that time. Tesla is currently advertising two trim levels: the Long Range Plus and the Performance. Both feature all-wheel drive and two electric motors, and they boast more than 300 miles of range. An industry-leading infotainment system, the largest touchscreen in the business, and breathtaking acceleration are also part of the Model X's appeal. Tesla says the Long Range Plus will hit 60 mph in 4.4 seconds, while the Performance will snap your neck with a time of just 2.6 seconds. Only the Porsche Taycan and Tesla's own Model S sedan can keep up with the X.",
image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/tesla-model-x-1581553912.jpg")

CarModel.create(category: "hatchback", brand: "Mini", model: "Electric", description: "Mini has been in and out of the EV business. This year, it's back in, with an updated version of its electrified Mini Cooper. The small front-wheel-drive hatchback is powered by a single electric motor mounted under its hood that generates 181 horsepower and 199 pound-feet of torque. The battery pack is under the floor, which gives the Electric a low center of gravity and preserves its cargo space. Three trim levels are offered with prices starting just over $30,000, but its 32.6-kWh battery pack is small, so range is limited to just 110 miles. Aside from radically styled asymmetric three-hole wheels—and, if you want, Energetic Yellow trim—it looks basically like every other Cooper, both inside and out. Mini even left the hood scoop in place. And it runs like a Mini, with athletic handling and a 60-mph sprint of about seven seconds.",
image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-mini-cooper-se-electric-110-1562683885.jpg")

CarModel.create(category: "hatchback", brand: "Nissan", model: "Leaf", description: "Now in its second generation, the Nissan Leaf has never been very sexy, but the compact five-door hatchback has been around for decade, and it's one of the best-selling electric vehicles in the world. A full redesign last year toned down the model's clumsy styling and increased its range. Two versions are now offered: the basic Leaf, with a 40.0-kWh battery pack, and the Plus, which costs about $7000 more. The Plus gets a 62.0-kWh battery pack for radically more range and a more powerful electric motor for better acceleration. Range jumps from 149 miles to a very respectable 226. Both versions of the Leaf are front-wheel drive and offer spacious cabins and a long list of standard and optional technologies, but it's not as fun to drive as its main rival, the Chevrolet Bolt, nor can it go as far on charge.",
image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2018-nissan-leaf-leadgallery-1589390514.jpg")

CarModel.create(category: "sedan", brand: "Tesla", model: "Model S", description: "There were EVs long before the Model S, but Tesla's sedanlike hatch is the vehicle that proved that an efficient, fast, and attractive electric will not only sell, it'll go for big money. Introduced way back in 2012, the Model S remains as appealing as ever, from its sleek muscular styling to its minimalistic interior. Its performance is still ahead of the industry that it dragged, kicking and screaming, into the EV business. Tesla has made improvements over the years, cranking up the hatchback's acceleration and range. Today, Tesla offers the Model S in either a Long Range Plus or a Performance trim. The latter will cost you $20,000 more. Both have all-wheel drive, two electric motors, and adjustable air suspension, and both are incredibly quick. Plus, the S offers the best range in the biz, up to 373 miles.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2020-porsche-taycan-turbo-s-and-2020-tesla-model-s-115-1581028003.jpg")

CarModel.create(category: "hatchback", brand: "Fiat", model: "500e", description: "The Fiat 500e is the smallest EV on this list and the one with the shortest range, at just 84 miles. This car was actually discontinued after the 2019 model year, but you can still get one if you live in California or Oregon. The cute little front-wheel-drive 500e is powered by a tiny 24.0-kWh lithium-ion battery pack and a single electric motor that generates 111 horsepower and 147 pound-feet of torque. With a 60-mph time of 8.4 seconds, it isn’t very quick, but it’s zippy around town and has light steering and fun handling thanks to a low center of gravity and teeny 90.6-inch wheelbase. The powertrain’s efficiency is also respectable, scoring a combined 112-MPGe rating from the EPA, which beats that of its main rival, the 2020 Mini Cooper SE, but the Mini is a bit larger, costs less, and offers more range.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2019-fiat-500e-gallery-exterior4-1589554443.jpg")

CarModel.create(category: "crossover", brand: "Kia", model: "Niro EV", description: "Introduced just last year, the Kia Niro EV has flown largely under the radar. That's unfortunate, as it offers considerable range, space, and style for a fair price. Part hatchback, part crossover, the four-door front-wheel-drive Niro EV is powered by the same 201-hp motor and 64.0-kWh battery pack used in the Hyundai Kona Electric. It's quick, with a 60-mph time of 6.5 seconds, and feels solid on the road, but it isn't very sporty to drive. It's also offered in only 12 states. Two trim levels are available. The list of standard features is long and includes adaptive cruise control, lane-centering assist, blind-spot monitoring, automated emergency braking, keyless entry, and 17-inch wheels. For 2020, Kia updated the EV with new headlamps and larger infotainment screens.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/16073-2020-niro-ev-1589399732.jpg")

CarModel.create(category: "crossover", brand: "BMW", model: "i3", description: "Although introduced way back in 2015, the i3 remains BMW's only EV. The quirky four-door has always been unconventional, with funky styling, unique rear doors that open \"suicide style,\" and a body made from carbon fiber. It's always been expensive, too. At more than $45,000, the i3 costs more than many rivals, but it offers only 153 miles of range, much less than what the cheaper Kia Niro EV, Chevy Bolt EV, Hyundai Kona Electric, and Tesla Model 3 can cover on a charge. Buyers can choose between the base i3 and the slightly sportier i3s, which gets standard 20-inch wheels and a more responsive suspension. Both are rear-wheel drive, which is unusual for an EV, and powered by a single 184-hp electric motor and a 33.2-kWh lithium-ion battery pack. In the base car, the run to 60 mph takes 6.6 seconds.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2018-bmw-i3s-ev-99leadgallery-1539275166.jpg")

CarModel.create(category: "hatchback", brand: "Chevrolet", model: "Bolt EV", description: "When the Chevy Bolt debuted back in 2016 with a range of 238 miles and a price below $40,000, the front-wheel-drive hatch seemed like the electric revolution most Americans were waiting for. Unfortunately, its homely little hatchback body turned many people off. This year, Chevy updated the Bolt's lithium-ion battery pack that's mounted under its floor, upping the energy density of the cells, and increasing its capacity from 60.0 kilowatt-hours to 66.0. According to the EPA, these changes have expanded its range by 21 miles, for a total of 259 miles. That's more than a Tesla Model 3 Short Range Plus has to offer, and the Bolt's 200-hp motor provides respectable thrust, with a 60-mph time of 6.7 seconds. We also like the Bolt's airy interior and decent 17 cubic feet of cargo space.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/d55-2166-1576528967.jpg")

CarModel.create(category: "crossover", brand: "Hyundai", model: "Kona Electric", description: "This is one of our favorite EVs. We were so impressed with the Hyundai Kona Electric that the compact crossover grabbed a spot on our 10Best Trucks and SUVs list its first year on the market. With spunky driving dynamics, impressive driving range, a generous warranty, a spacious interior, and attractive styling, the Kona checks all the boxes. Plus, it's competitively priced, offering an EPA-rated range of 258 miles on a single charge for less than $40,000. If you were hoping for all-wheel drive, however, you're out of luck. It isn't offered on the Kona Electric. A 64.0-kWh battery pack feeds a 201-hp electric motor, which drives the front wheels. At the test track, the Hyundai hit 60 mph in 6.4 seconds, 0.2 second quicker than the regular Kona.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2019-hyundai-kona-electric-comparison-103-1550686826-1-1589390516.jpg")

CarModel.create(category: "crossover", brand: "Tesla", model: "Model Y", description: "The Tesla Model Y is basically a crossover version of the Model 3, but don't let its looks fool you. It's larger than it appears. At 187 inches long, the Y is about five inches longer than a Honda CR-V and nearly three inches wider, but it sits more than two inches lower than that mainstream crossover. Its rounded design is right out of Tesla's playbook, sort of a cross between the Model 3 and the Model X. It is handsome and sure to be a wallet opener. We expect the market will embrace the Y's sub-$55,000 base price and 300-plus-mile range. Powertrains are shared with the Model 3. Tesla promises a rear-wheel-drive Standard Range model for next year. For now, though, there are two all-wheel-drive models on offer: the Long Range (which awaits its EPA ratings) and the Performance. Both feature two electric motors, and Tesla says the latter can hit 60 mph in 3.5 seconds.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/model-y-front-34-blue-1552622911.jpg")

CarModel.create(category: "hatchback", brand: "Hyundai", model: "Ioniq Electric", description: "The Hyundai Ioniq Electric hatchback is about the size of a Toyota Prius. Sold in only a handful of states, the all-electric version costs about $34,000 and has an impressive combined fuel-economy rating of 133 MPGe, but its battery pack is small, and its range falls near the bottom of current EV offerings. This year, the Ioniq's battery capacity increases from 28.0 kilowatt-hours to 38.3. This has expanded the car's driving range from just 124 miles to a more respectable 170 miles. The Ioniq's horsepower also increases from 118 to 134, but the powertrain's refinement could perhaps be better. To entice new buyers, Hyundai has recently given the spritely front-wheel-drive hatchback a mild styling update, a larger infotainment touchscreen, and more active safety features, including adaptive cruise control and automated emergency braking.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/large-39301-2020ioniqelectric-1589400303.jpg")

CarModel.create(category: "sedan", brand: "Tesla", model: "Model 3", description: "Regardless of how you feel about Elon Musk or Tesla products, there's no denying the sales success of the Model 3. Introduced a few years ago, the brand's least expensive model was one of the most anticipated cars of the decade, promising huge EV range for about $40,000. Today, they're everywhere, and it's easy to understand the appeal. The Model 3 is a quick sharp-handling sedan with attractive styling and enough interior space for your friends. It also offers the biggest range numbers and the lowest acceleration times for the money. Musk has delivered the bang for the buck. The rear-wheel-drive Standard Range Plus model with its 250 miles of range has proven exceedingly popular, while the all-wheel-drive Long Range and Performance models offer 322 miles of range and 60-mph acceleration as quick as 3.2 seconds.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2019-tesla-model-3-101-1574807022.jpg")

CarModel.create(category: "sport sedan", brand: "Fisker", model: "Karma", description: "The Fisker Karma was revealed at the 2008 North American International Auto Show in Detroit. It was the first car from Fisker Automotive, a then new auto maker based in Anaheim, California, founded on September 5, 2007. Production began in July 2011, and the first two deliveries took place in the United States on July 26, 2011. In October 2011 the first Karma delivered in the UK was auctioned to benefit Pratham UK and raised a bid of GB£140,000 (around US$220,000). Following the sale to Chinese company Wanxiang of assets, designs, rights to a plug-hybrid powertrain, and a manufacturing facility in Delaware, the new owners in September 2016 commenced production under the name Karma Automotive. After several announcements by Wanxiang Group to reintroduce an upgraded version of the Fisker Karma, it has been renamed the Karma Revero and launched with booking scheduled then too.", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Fisker_Karma_EVer_EcoChic_%E2%80%93_Frontansicht_%281%29%2C_6._Juni_2012%2C_D%C3%BCsseldorf.jpg/280px-Fisker_Karma_EVer_EcoChic_%E2%80%93_Frontansicht_%281%29%2C_6._Juni_2012%2C_D%C3%BCsseldorf.jpg")

CarModel.create(category: "sport sedan", brand: "Ford", model: "Mustang Mach-E", description: "The past and the future collide on the 2021 Ford Mustang Mach-E, which is inspired by the automaker's unmistakable pony car and powered exclusively by electricity. Although it shares a name and familiar styling cues with the Mustang, the all-electric crossover otherwise is completely unrelated. With two available battery sizes and either rear- or all-wheel drive, Ford says the Mach-E can provide up to 300 miles of driving range. Its five-passenger cabin is fitted with contemporary features and cutting-edge infotainment options as well as some unique cargo and storage solutions. While purists might call an electric Mustang crossover sacrilegious, Ford expects the name and design adaptation to increase interest and help sell a lot of copies of the 2021 Mach-E.", image_url: "https://www.carscoops.com/wp-content/uploads/2019/11/2021-Ford-Mustang-Mach-E-4X-First-Edition-0.jpg")

CarModel.create(category: "truck", brand: "Tesla", model: "Cybertruck", description: "The Tesla Cybertruck looks like it was dropped off by an alien race, but it has the capabilities to challenge all of the top-selling pickup trucks. With a sharp-edged exterior that is made of scratch- and dent-resistant stainless steel, Tesla's all-electric truck is seriously tough. Along with available all-wheel drive, the Cybertruck can tow up to 14,000 pounds and has an estimated driving range of 500-plus miles. While that applies only to the most expensive model, the cheapest one starts at $39,900. Of course, there's still a lot we don't know about the Cybertruck, including when it will officially go on sale. Right now, it looks as if the first versions will go into production in late 2021.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2022-tesla-cyber-truck-mmp-1-1579127142.jpg")

CarModel.create(category: "sedan", brand: "Polestar", model: "2", description: "Following in the footsteps of the plug-in hybrid Polestar 1, the all-electric 2021 Polestar 2 is—as the name implies—the second creation from Volvo's standalone performance brand. Trying to be all things to all people, the design blends the three-box proportions of a sedan with a sloping roof, a rear hatch, and the raised ride height of a crossover. While the Polestar's minimalist appearance borders on anonymous, its cabin is the epitome of engrossing and contains a potentially revolutionary infotainment system. Its twin electric motors provide prodigious quickness and there's a satisfying amount of engagement when the driver seeks it out. With the 2's ambiguous body style, Polestar attempts the two-birds-one-stone method to combat the Tesla Model 3 and Model Y in terms of technology and performance. But, for now, it's still short on range and recognition.", image_url: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-polestar-2-104-1596482504.jpg")

CarModel.create(category: "sport sedan", brand: "Aspark", model: "Owl", description: "Japan’s nascent electric hypercar company has wasted no time in staking its claim to the title of ‘world’s quickest car’. Powered by four electric motors with a staggering combined output of 1985bhp, the Owl has already rattled off the 0-60mph sprint in 1.72sec, and its creators reckon there’s the potential to shave a further few tenths from this figure. Top speed is claimed to be 249mph, while the specially developed 64kWh battery gives a claimed range of 280 miles. Aspark plans to build just 50 examples of the Owl, each priced at a cool £2.5 million.", image_url: "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/body-image/public/10-aspark-owl-side.jpg")


20.times do
    OwnedCar.create(color: Faker::Color.color_name, year: Faker::Vehicle.year, price_per_day: Faker::Commerce.price, city: Faker::Address.city, car_model: CarModel.all.sample, user: User.all.sample)
end

20.times do
    Booking.create(owned_car: OwnedCar.all.sample, user: User.all.sample, pickup_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 14.day), dropoff_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 14.day))
end

20.times do
    Review.create(booking: Booking.all.sample, user: User.all.sample, description: Faker::Lorem.paragraphs, star_rating: rand(1..10))
end

20.times do
    WishListCar.create(car_model: CarModel.all.sample , user: User.all.sample)
end

#admin account
User.create!(name: "admin", email: "admin", password: "password", password_confirmation: "password", admin: true)


puts "running seeds"
